### ISSUE TITLE
can it be built by VS2008？

### ISSUE THREAD

**Issue by xunkaixin** [ChrislS/caffe-brewer#1]

**Comment by classner** [comment]
Hi!
The short answer is: no! The longer answer is a little more elaborate.

Basically, the "caffe-brewer" project _should_ not need any modifications to build with VS2008. I submitted a pull request to the caffe core project (which probably brought you to this page) with a minimal changeset (https://github.com/BVLC/caffe/pull/2136) to allow compilation of that project with the MSVC toolchain. These are really not many, as you can see in the pull request diff.

It was necessary to replace some of the UNIX or GCC specific commands with MSVC or C++ standard equivalents, and simply because it was handy, I used C++11. VS2008 does not support this yet, and the first version of Visual Studio that does is VS2012. However, if you take the time to again replace the replacements with non C++ 11 ones (and there are no problems with nvcc using VS2008), then it should be possible. It will be a bit of work, and might get a "rough ride" though...
